### ISSUE TITLE
Leaking credentials via JS file

### ISSUE THREAD

**Issue by CristiVlad25** [omoniyi289/leap-api#2]
Hello, you're leaking credentials via this file:

https://github.com/omoniyi289/leap-api/blob/71ebefc000f8f515a0c27786a6214c742175d896/common/config/env.config.js

If that's unintentional, make sure to set appropriate access controls so that your keys are not abused by unauthorized parties.

Regards

**Comment by omoniyi289** [comment]
thanks. corrected
